title: Settings
data:
  site_name: 'Marc Young'
  social:
    -
      id: RDN5BZUU
      name: Linkedin
      url: 'https://twitter.com/jackmcdade'
      icon: site/social-icons/linkedin-svgrepo-com.svg
    -
      id: BC018742
      name: Github
      url: 'https://github.com/mdyoung3'
      icon: site/social-icons/github.svg
    -
      id: NLmRw1O6
      name: Email
      url: 'mailto:marcdeeyoung@proton.me'
      icon: site/social-icons/email.svg
